<a href="https://colab.research.google.com/github/royalmaj/book/blob/main/basic_operation_of_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


arr_1d = np.array([1, 2, 3, 4, 5])

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   [[7, 8, 9],
                    [10, 11, 12]]])

print("1D Array:")
print("Shape:", arr_1d.shape)
print("Size:", arr_1d.size)
print("Dimension:", arr_1d.ndim)
print("Length:", len(arr_1d))

print("\n2D Array:")
print("Shape:", arr_2d.shape)
print("Size:", arr_2d.size)
print("Dimension:", arr_2d.ndim)
print("Length:", len(arr_2d))

print("\n3D Array:")
print("Shape:", arr_3d.shape)
print("Size:", arr_3d.size)
print("Dimension:", arr_3d.ndim)
print("Length:", len(arr_3d))


1D Array:
Shape: (5,)
Size: 5
Dimension: 1
Length: 5

2D Array:
Shape: (2, 3)
Size: 6
Dimension: 2
Length: 2

3D Array:
Shape: (2, 2, 3)
Size: 12
Dimension: 3
Length: 2


In [2]:
import numpy as np

arr_arange = np.arange(0, 10, 2)
print("np.arange():", arr_arange)

arr_randint = np.random.randint(1, 100, size=(3, 3))
print("np.random.randint():\n", arr_randint)

arr_rand = np.random.rand(2, 3)
print("np.random.rand():\n", arr_rand)

arr_linspace = np.linspace(0, 10, num=5)
print("np.linspace():", arr_linspace)

arr_ones = np.ones((2, 3))
print("np.ones():\n", arr_ones)

arr_zeros = np.zeros((3, 2))
print("np.zeros():\n", arr_zeros)

arr_diag = np.diag([1, 2, 3])
print("np.diag():\n", arr_diag)

arr_sum = np.sum(arr_randint)
print("np.sum():", arr_sum)

arr_min = np.min(arr_randint)
print("np.min():", arr_min)

arr_max = np.max(arr_randint)
print("np.max():", arr_max)

arr_mean = np.mean(arr_randint)
print("np.mean():", arr_mean)


np.arange(): [0 2 4 6 8]
np.random.randint():
 [[16 35 92]
 [33 63 59]
 [42 70  6]]
np.random.rand():
 [[0.81604639 0.41683516 0.72808511]
 [0.11735208 0.97595525 0.4130751 ]]
np.linspace(): [ 0.   2.5  5.   7.5 10. ]
np.ones():
 [[1. 1. 1.]
 [1. 1. 1.]]
np.zeros():
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
np.diag():
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
np.sum(): 416
np.min(): 6
np.max(): 92
np.mean(): 46.22222222222222


In [3]:
import random


num_students = 50
student_marks = [random.randint(0, 100) for _ in range(num_students)]


def filter_failed_marks(marks):
    return [mark for mark in marks if mark < 30]

def count_passed_students(marks):
    passed_count = sum(1 for mark in marks if mark >= 30)
    return passed_count

passed_students = count_passed_students(student_marks)


failed_marks = filter_failed_marks(student_marks)


print("Number of students who passed:", passed_students)
print("Failed marks:", failed_marks)


Number of students who passed: 39
Failed marks: [24, 5, 24, 8, 2, 21, 20, 16, 4, 28, 28]


In [4]:
import numpy as np


random_2d_array = np.random.randint(1, 51, size=(3, 4))

print(random_2d_array)


[[20 42 23  7]
 [ 2 29 11 42]
 [36 21  9 14]]


In [5]:
import numpy as np


odd_numbers_array = np.arange(-29, 11, 2)

print(odd_numbers_array)


[-29 -27 -25 -23 -21 -19 -17 -15 -13 -11  -9  -7  -5  -3  -1   1   3   5
   7   9]
